name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s
          ./bin/golangci-lint run -v
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: true
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - uses: actions/checkout@v2
      - run: go build ./...
      - run: go test -v ./...