name: CI
on:
  push:
    branches:
      - 'master'

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate
        run: |
          go run cmd/main.go
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}